# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: ['v*']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Helps set up MSBuild into PATH for later usage
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      # build
      - name: msbuild
        shell: cmd
        run: |
          curl -L -O "https://sourceforge.net/projects/vjoystick/files/Beta 2.x/2.1.9.1-160719/SDK.zip"
          "c:\Program Files\7-Zip\7z.exe" x SDK.zip
          msbuild /p:platform=x86 /p:Configuration=Release
          msbuild /p:platform=x64 /p:Configuration=Release
      # upload
      - name: Upload release binaries
        if: contains(github.ref, 'tags/v')
        shell: bash
        run: |
          set -x
          assets=()
          for asset in ./ds5*.zip; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release edit "${assets[@]}" -m "" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
